/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupplyChainRouteImport } from './routes/supply-chain'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsTurmericRouteImport } from './routes/products.turmeric'
import { Route as ProductsRedChilliRouteImport } from './routes/products.red-chilli'
import { Route as ProductsMoringaRouteImport } from './routes/products.moringa'
import { Route as ProductsCardamomRouteImport } from './routes/products.cardamom'
import { Route as ProductsBlackPepperRouteImport } from './routes/products.black-pepper'

const SupplyChainRoute = SupplyChainRouteImport.update({
  id: '/supply-chain',
  path: '/supply-chain',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsTurmericRoute = ProductsTurmericRouteImport.update({
  id: '/turmeric',
  path: '/turmeric',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsRedChilliRoute = ProductsRedChilliRouteImport.update({
  id: '/red-chilli',
  path: '/red-chilli',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsMoringaRoute = ProductsMoringaRouteImport.update({
  id: '/moringa',
  path: '/moringa',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsCardamomRoute = ProductsCardamomRouteImport.update({
  id: '/cardamom',
  path: '/cardamom',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsBlackPepperRoute = ProductsBlackPepperRouteImport.update({
  id: '/black-pepper',
  path: '/black-pepper',
  getParentRoute: () => ProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supply-chain': typeof SupplyChainRoute
  '/products/black-pepper': typeof ProductsBlackPepperRoute
  '/products/cardamom': typeof ProductsCardamomRoute
  '/products/moringa': typeof ProductsMoringaRoute
  '/products/red-chilli': typeof ProductsRedChilliRoute
  '/products/turmeric': typeof ProductsTurmericRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supply-chain': typeof SupplyChainRoute
  '/products/black-pepper': typeof ProductsBlackPepperRoute
  '/products/cardamom': typeof ProductsCardamomRoute
  '/products/moringa': typeof ProductsMoringaRoute
  '/products/red-chilli': typeof ProductsRedChilliRoute
  '/products/turmeric': typeof ProductsTurmericRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supply-chain': typeof SupplyChainRoute
  '/products/black-pepper': typeof ProductsBlackPepperRoute
  '/products/cardamom': typeof ProductsCardamomRoute
  '/products/moringa': typeof ProductsMoringaRoute
  '/products/red-chilli': typeof ProductsRedChilliRoute
  '/products/turmeric': typeof ProductsTurmericRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/products'
    | '/sitemap.xml'
    | '/supply-chain'
    | '/products/black-pepper'
    | '/products/cardamom'
    | '/products/moringa'
    | '/products/red-chilli'
    | '/products/turmeric'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/supply-chain'
    | '/products/black-pepper'
    | '/products/cardamom'
    | '/products/moringa'
    | '/products/red-chilli'
    | '/products/turmeric'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/products'
    | '/sitemap.xml'
    | '/supply-chain'
    | '/products/black-pepper'
    | '/products/cardamom'
    | '/products/moringa'
    | '/products/red-chilli'
    | '/products/turmeric'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupplyChainRoute: typeof SupplyChainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supply-chain': {
      id: '/supply-chain'
      path: '/supply-chain'
      fullPath: '/supply-chain'
      preLoaderRoute: typeof SupplyChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/turmeric': {
      id: '/products/turmeric'
      path: '/turmeric'
      fullPath: '/products/turmeric'
      preLoaderRoute: typeof ProductsTurmericRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/red-chilli': {
      id: '/products/red-chilli'
      path: '/red-chilli'
      fullPath: '/products/red-chilli'
      preLoaderRoute: typeof ProductsRedChilliRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/moringa': {
      id: '/products/moringa'
      path: '/moringa'
      fullPath: '/products/moringa'
      preLoaderRoute: typeof ProductsMoringaRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/cardamom': {
      id: '/products/cardamom'
      path: '/cardamom'
      fullPath: '/products/cardamom'
      preLoaderRoute: typeof ProductsCardamomRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/black-pepper': {
      id: '/products/black-pepper'
      path: '/black-pepper'
      fullPath: '/products/black-pepper'
      preLoaderRoute: typeof ProductsBlackPepperRouteImport
      parentRoute: typeof ProductsRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsBlackPepperRoute: typeof ProductsBlackPepperRoute
  ProductsCardamomRoute: typeof ProductsCardamomRoute
  ProductsMoringaRoute: typeof ProductsMoringaRoute
  ProductsRedChilliRoute: typeof ProductsRedChilliRoute
  ProductsTurmericRoute: typeof ProductsTurmericRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsBlackPepperRoute: ProductsBlackPepperRoute,
  ProductsCardamomRoute: ProductsCardamomRoute,
  ProductsMoringaRoute: ProductsMoringaRoute,
  ProductsRedChilliRoute: ProductsRedChilliRoute,
  ProductsTurmericRoute: ProductsTurmericRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProductsRoute: ProductsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupplyChainRoute: SupplyChainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
